### ISSUE TITLE
TCP not reconnecting when connection is reset by remote server

### ISSUE THREAD

**Issue by cipriancraciun** [systemd/systemd-netlogd#104]
I have built the latest `v1.4` code on OpenSUSE Leap 15.5, and I've tried to push the messages to a remote TCP syslog server.

However, if the remote syslog server restarts, thus resetting the TCP connection, `systemd-netlogd` fails to detect the broken connection and thus fails to try to reconnect.

`strace`-ing the `systemd-netlogd` process yields the following events (that pertain to network activity):
* before the remote server is restarted, thus before resetting the connection, `systemd-networkd` issues the `sendmsg` syscall to which it receives a positive outcome;
* however, after the remote server is restarted, when `systemd-networkd` tries to `sendmsg` the next message, it gets the following syscall return `-1 EPIPE (Broken pipe)`
* from here onwards, it tries to resend the same message over and over, without trying to reconnect;

**Comment by ssahani** [comment]
Please test with https://github.com/systemd/systemd-netlogd/pull/105

**Comment by cipriancraciun** [comment]
I've just tasted with latest main commit (that includes the pull you've mentioned), and apparently it works as expected now.

Thanks!
