### ISSUE TITLE
`--version` does not accurately report version 

### ISSUE THREAD

**Issue by getchoo** [systemd/systemd-netlogd#112]
As of 1.4.1, the project version is misreported as `1.4` when running `systemd-netlogd --version`. I'm not sure if this was intentional or a forgotten bump in [meson.build](https://github.com/systemd/systemd-netlogd/blob/fc4793795c9596876d795ef6c838ce73c2a039bb/meson.build#L2), but it would be nice to have the correct patch version included in this output in future releases

**Comment by ssahani** [comment]
Happy to take q patch

**Comment by ssahani** [comment]
Closing as completed https://github.com/systemd/systemd-netlogd/pull/113
