### ISSUE TITLE
[Feature Request] Add filtering for categories?

### ISSUE THREAD

**Issue by vipergts450** [systemd/systemd-netlogd#120]
Hello,

Thanks for this project as it has become very useful for consolidating log files into a syslog server. Apologies if this is out of the scope of the project, but is it possible to filter logs so that auth and authpriv messages (as a small example) are filtered out before sending to the syslog server? rsyslog.conf has this filtering by default, and apologies if I have missed it as one of your listed options, but none seemed to match the intention.

Thanks.

**Comment by ssahani** [comment]
@cgzones without regex etc I think we can do this.

**Comment by cgzones** [comment]
Should be possible with #134
