### ISSUE TITLE
Documentation comparing with other tools?

### ISSUE THREAD

**Issue by mikepurvis** [systemd/systemd-netlogd#16]
I'm here via https://github.com/systemd/systemd/issues/7170, and seeking to understand the potential advantages of using systemd-netlogd vs just flipping on `ForwardToSyslog` and then using rsyslog, syslog-ng, or various other tools which can toss those messages onto the wire.

Is this just a case of systemd avoiding an external dependency, or are there additional capabilities or efficiencies here which I'm not seeing?

**Comment by ssahani** [comment]
>Is this just a case of systemd avoiding an external dependency, or are there additional capabilities or efficiencies here which I'm not seeing?

Well it's not included in systemd project . It's external

>I'm here via systemd/systemd#7170, and seeking to understand the potential advantages of using systemd-netlogd vs just flipping on ForwardToSyslog and then using rsyslog, syslog-ng, or various other tools which can toss those messages onto the wire.

It just reads from journal and forwards to network one by one. It does not use extra disk space. Relies on networkd. When network is down it immediately stop sending to network and network back online it starts from that exact position . Very tiny daemon .

**Comment by mikepurvis** [comment]
Cool, thanks for the info— perhaps consider updating the repo's readme to include this, for the sake of future travellers?

**Comment by q2dg** [comment]
So, on the other side of the wire it continues to be imperative to use some other program like rsyslog or syslog-ng to store these logs sent by systemd-netlogd? Couldn't it be systemd-journald-remote?
