### ISSUE TITLE
Failed to get cursor

### ISSUE THREAD

**Issue by dreh23** [systemd/systemd-netlogd#17]
After running for a while systemd-netlogd gets into a failed state.
```
Jun 22 21:15:09 node1.pi-jaas-kube1.kubernetes.cluster.int systemd[1]: Started systemd-netlogd.service.
Jun 23 08:10:43 node1.pi-jaas-kube1.kubernetes.cluster.int systemd-netlogd[18915]: Failed to get cursor: Cannot assign requested address
```
I believe this is a duplicate of #14 and the problem is not solved . We are using latest commit (9ae17f5931fbac8e8de78d84f37855af8015a6a0) .

This happens on a production cluster on all 25 nodes.

compiled with gperf 3.1 on debian:stretch
```

core@node4[pi-jaas-kube1] ~ $ /opt/bin/systemd-netlogd --version
systemd-netlogd 1
-PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL -XZ -LZ4 -SECCOMP -BLKID -ELFUTILS -KMOD -IDN
```
Production OS is coreos-1688.5.3

If needed I can provide an strace. Since this just happens on the production machine after several hours this is not ideal.

**Comment by dreh23** [comment]
Thanks ssahani. Patch is deployed on 4 nodes. Will report back today or tomorrow on success/failure.

**Comment by dreh23** [comment]
Syslog team confirms nodes are still sending logs after several hours, although we still see the error message - is this an expected behaviour?

**Comment by ssahani** [comment]
I have not removed the error message It will be still there . Since it got failed via some means like log rotation etc the cursor got lost  And needs to be reset.
