### ISSUE TITLE
Default configuration doesn't work

### ISSUE THREAD

**Issue by guruevi** [systemd/systemd-netlogd#20]
Since this crucial piece of systemd is not yet in Ubuntu distribution, I compiled it from scratch. No errors, I put in a configuration and enabled and started systemd-netlogd.

I get the following error:
Aug 07 10:30:26 dicom systemd[1]: Started Journal Syslog Unicast and Multicast Daemon.
Aug 07 10:30:27 dicom systemd[1]: systemd-netlogd.service: Main process exited, code=exited, status=1/FAILURE
Aug 07 10:30:27 dicom systemd[1]: systemd-netlogd.service: Failed with result 'exit-code'.

**Comment by ssahani** [comment]
No info to debug with. Please start manually from command line ```SYSTEMD_LOG_LEVEL=debug ./systemd-netlogd'``` and paste the logs

**Comment by bachp** [comment]
I think the problem is that the default `systemd-netlogd.conf` has the `Address` commented out. As `systemd-netlogd` doesn't know what to do in that case it just exists with exit code 1.

**Comment by daringer** [comment]
Yes, can confirm that the example does not work out-of-the-box ... Despite that it seems mandatory to provide an IP and not a hostname as no resolving seems to happen

**Comment by ssahani** [comment]
Yes you need to put the address.
