### ISSUE TITLE
Service doesn't start

### ISSUE THREAD

**Issue by dhyaman** [systemd/systemd-netlogd#21]
Hi,

I cant start the service with systemd always produce error below,

Dec 17 17:16:56 cybertron systemd-netlogd[17649]: Failed to drop auxiliary groups list: Operation not permitted
What is mean how to solve this issue?

Thanks.

**Comment by ssahani** [comment]
How do I reproduce it. Could you please be more informative. Which environment sort of thing

**Comment by ssahani** [comment]
Closing because of lack of response
