### ISSUE TITLE
Integrate with Travis CI

### ISSUE THREAD

**Issue by ssahani** [systemd/systemd-netlogd#25]
@evverx Seems like some kind of permission required . Could you please approve it.

**Comment by evverx** [comment]
I've just activated the repository on Travis.

**Comment by ssahani** [comment]
Thank you :)

**Comment by evverx** [comment]
I triggered it manually and it seems to be working: [![Build Status](https://travis-ci.org/systemd/systemd-netlogd.svg?branch=master)](https://travis-ci.org/systemd/systemd-netlogd) :-)

**Comment by ssahani** [comment]
yeah gperf  need to be installed :) I will modify the yaml file. thanks.
