### ISSUE TITLE
Provide more info about StructuredData

### ISSUE THREAD

**Issue by lzap** [systemd/systemd-netlogd#3]
Greetings, I am evaluating options of remote logging for our deployment and I would like to know more about StructuredData support - what kind of format does it use? Can you add some links? Thanks!

**Comment by ssahani** [comment]
@san-skov-dk Could you please answer this .

**Comment by san-skov-dk** [comment]
We had been using systemd-netlog for logging to Loggly. 
Loggly are using structured data in the log feed to find out, which customer is currently logging and separates log from this. 
More description here https://www.loggly.com/docs/automated-parsing
I only knows Logglys format, which is described at the page above.

**Comment by lzap** [comment]
Oh thanks!
