### ISSUE TITLE
[Feature Request] Support for TLS

### ISSUE THREAD

**Issue by fpoirotte** [systemd/systemd-netlogd#36]
Hi,

Similar to the comment at https://github.com/systemd/systemd-netlogd/issues/24#issuecomment-779980626, I think it would be great if systemd-netlogd had TLS support.
It should at least be able to authenticate the remote server where the logs are being forwarded to. Ideally though, it would also be able to authenticate the client (so that both the sender and recipient can mutually authenticate each other).

Cheers,
François

**Comment by ssahani** [comment]
I have started working on it https://github.com/systemd/systemd-netlogd/commit/c6f5c01d39faddc6b1f905b3f1160e8c2c29123d

**Comment by rmcuenen** [comment]
Is there already a release planned for this feature?

**Comment by ssahani** [comment]
I have introduced DTLS https://github.com/systemd/systemd-netlogd/pull/55

**Comment by ssahani** [comment]
Closed via https://github.com/systemd/systemd-netlogd/pull/57
