### ISSUE TITLE
Question: systemd-netlogd, LogNamespace

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [systemd/systemd-netlogd#37]
Nobody seems to have an idea on stackexchange, so I'll try here:

I'm working on a system (embedded device) on which a specific systemd service is running in its own LogNamespace:

[Service]
LogNamespace=foo
This is done so this service can log into persistent storage whereas all the other logs are volatile.

Also, on the same system logs are forwarded via systemd-netlogd. This works well for all other services and such but does not work for the service in its own namespace.

The systemd-netlogd configuration (https://github.com/systemd/systemd-netlogd) doesn't offer any parameter regarding a LogNamespace. Thus, as far as I can see it's not possible to run a 2nd instance of systemd-netlogd responsible for the 2nd instance of systemd-journald which itself handles the special LogNamespace.

Is it possible to get systemd-netlogd to work with LogNamespace? If yes: How?

**Comment by ssahani** [comment]
Please test with  Namespace=
