### ISSUE TITLE
[Feature Request] Avoid conversion to RFC 5424

### ISSUE THREAD

**Issue by TommasoCostanzo** [systemd/systemd-netlogd#39]
I tried to forward the syslog to Wazuh manager, and it works great. Unfortunately, Wazuh does not support RFC 5424 and the development there seems to not proceed in that direction. So I have tried to check the code, but unfortunately I am not that familiar with C and I cannot do it by myself. However, if I am not wrong, the string that is pushed to the network is generated in the function "manager_push_to_network". So, I would hope that in that function you can add some condition that can be triggered with a runtime flag that passes the raw journal string as printed by journalctl instead of recombining it to make it RFC 5424 compliant. I that way Wazuh will be happy and it will decode properly the string.
If this is too complex for you, I will go for the suggested way from Wazuh, that is to write the log into a file and have the wazuh agent reading from the file. But that is a bit annoying because of the log duplication.

I any case thank you very much for your effort and the code!

**Comment by glance-** [comment]
I needed OLD STYLE rfc3339 logs so I did a quite ugly hack in https://github.com/glance-/systemd-netlogd/commit/fffc70c7c78ab94431dd20e55408b8187909a140 

It should probably be generalized and configurable but this was good enough for me.

**Comment by ssahani** [comment]
Implemented with https://github.com/systemd/systemd-netlogd/commit/1cade3757bb91e7bb05bde7410d7bb454bdedd17
