### ISSUE TITLE
Permission denied accessing /var/log/journal

### ISSUE THREAD

**Issue by sqwishy** [systemd/systemd-netlogd#7]
strace shows:
```
open("/var/log/journal/d1eb468c593f467c9a5e6d6d70bcbf88/system.journal", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
```
I ran `useradd -G systemd-journal systemd-journal-netlog`, htop shows that the service is running as that user. I don't get this error when I don't call `drop_privileges()`

Filesystem permissions look good to me.
```
# ls -lhd /var/log/journal/ /var/log/journal/d1eb468c593f467c9a5e6d6d70bcbf88/ /var/log/journal/d1eb468c593f467c9a5e6d6d70bcbf88/system.journal
drwxr-sr-x+ 1 root systemd-journal   64 Jun 21  2017 /var/log/journal//
drwxr-sr-x+ 1 root systemd-journal 5.5K Feb  2 00:26 /var/log/journal/d1eb468c593f467c9a5e6d6d70bcbf88//
-rw-r-----+ 1 root systemd-journal  16M Feb  2 01:25 /var/log/journal/d1eb468c593f467c9a5e6d6d70bcbf88/system.journal
```
I can read the file fine when sudoing as the systemd-journal-netlog user.
This is running under an LXC but I don't see how that would affect anything.

Do you know what might be going on?

Also, a second question that I figured wasn't really worth opening another issue for...

It looks like systemd-netlogd is trying to send oversized UDP packets and they're being truncated.
```
16:08:37.805134 IP (tos 0x0, ttl 63, id 24660, offset 0, flags [+], proto UDP (17), length 1500)
    10.100.0.160.45119 > 10.100.0.20.iop: UDP, bad length 2012 > 1472
16:08:37.805285 IP (tos 0x0, ttl 63, id 24661, offset 0, flags [+], proto UDP (17), length 1500)
    10.100.0.160.45119 > 10.100.0.20.iop: UDP, bad length 1990 > 1472
```
From what little I know about the syslog format, they don't really support handling fragmented UDP packets in the protocol and this program is conforming to specification. I'm just bringing this up so you can confirm that or correct me if I'm mistaken.

**Comment by noahwilliamsson** [comment]
@sqwishy See #10 (systemd-journal as supplementary group not supported).  Systemd-netlogd drops supplementrary groups as part of dropping privileges and therefore it cannot access the journals unless it's running under a user whose primary group is `systemd-journal`.

Try something like:

```
# Delete any files owned by the current systemd-journal-netlog user, then:
userdel systemd-journal-netlog
useradd -r -d / -s /usr/sbin/nologin -g systemd-journal systemd-journal-netlog
```

**Comment by ssahani** [comment]
It looks like systemd-netlogd is trying to send oversized UDP packets and they're being truncated.
I think this could be possible scenario as netlogd does not check the size of the message.

**Comment by ssahani** [comment]
Also look for offloading flags is your network card handling fragmentation. Ethtool - k

**Comment by daringer** [comment]
This (the permission issue, due to not being considered as part of `systemd-journal` is in fact the 2nd show-stopper once the configuration "issue" has been resolved, for me the workaround is as @noahwilliamsson stated to remove and re-add the user as he pointed out.

Nevertheless this is likely an arch-linux specifc, as the user adding process is done using some `.sysusers` file. Trying also to address this via the [Archlinux AUR](https://aur.archlinux.org/packages/systemd-netlogd/) 

Once this was fixed, things run nice and smooth!

**Comment by hitsmaxft** [comment]
systemd-journal-netlog should   adding with primary group systemd-journal, skipping  group systemd-journal-netlog creating

here is my /usr/lib/sysusers.d/systemd-netlogd.conf
```
#Type   Name                    ID                      GECOS   Home directory  Shell
u       systemd-journal-netlog  -:systemd-journal       -       /               /bin/nologin
```

**Comment by hitsmaxft** [comment]
systemd-journal-netlog should   adding with primary group systemd-journal, skipping  group systemd-journal-netlog creating

```
#Type   Name                    ID                      GECOS   Home directory  Shell
u       systemd-journal-netlog  -:systemd-journal       -       /               /bin/nologin
```
